{"timestamp":"2025-06-29T10:50:44.587486","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-29T10:50:44.588090","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airdag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-29T10:50:44.733447","level":"info","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.22.0.4', 9092)]>: connecting to kafka:9092 [('172.22.0.4', 9092) IPv4]","logger":"kafka.conn"}
{"timestamp":"2025-06-29T10:50:44.735921","level":"info","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.22.0.4', 9092)]>: Broker version identified as 2.6","logger":"kafka.conn"}
{"timestamp":"2025-06-29T10:50:44.736605","level":"info","event":"<BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.22.0.4', 9092)]>: Connection complete.","logger":"kafka.conn"}
{"timestamp":"2025-06-29T10:50:44.765953Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.766383Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.766634Z","level":"info","event":"Current task name:Sending_to_postgres","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.766867Z","level":"info","event":"Dag name:api-kafka-postgres","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.767110Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.767338Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.767553Z","level":"info","event":"Task:<Task(PythonOperator): Sending_to_postgres>","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.767768Z","level":"info","event":"Failure caused by connection to server at \"localhost\" (::1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.767986Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.768208Z","level":"info","event":"connection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.768424Z","level":"info","event":"\tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.768646Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-29T10:50:44.752897","level":"info","event":"<BrokerConnection client_id=kafka-python-2.2.14, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.22.0.4', 9092)]>: connecting to kafka:9092 [('172.22.0.4', 9092) IPv4]","logger":"kafka.conn"}
{"timestamp":"2025-06-29T10:50:44.755172","level":"info","event":"<BrokerConnection client_id=kafka-python-2.2.14, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.22.0.4', 9092)]>: Broker version identified as 2.6","logger":"kafka.conn"}
{"timestamp":"2025-06-29T10:50:44.755348","level":"info","event":"<BrokerConnection client_id=kafka-python-2.2.14, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.22.0.4', 9092)]>: Connection complete.","logger":"kafka.conn"}
{"timestamp":"2025-06-29T10:50:44.755775","level":"warning","event":"group_id is None: disabling auto-commit.","logger":"kafka.coordinator.consumer"}
{"timestamp":"2025-06-29T10:50:44.756474","level":"info","event":"Updating subscribed topics to: ('products',)","logger":"kafka.consumer.subscription_state"}
{"timestamp":"2025-06-29T10:50:44.757793","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"localhost\" (::1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\nconnection to server at \"localhost\" (127.0.0.1), port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1154,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/data_consumer.py","lineno":22,"name":"consume_and_store_products"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
